---

- ansible.builtin.include_tasks: bash_profile.yml

- name: More User Friendly List Aliases
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
    state: present
  loop:
    - { alias: ll, command: "ls -lFh" }
    - { alias: la, command: "ls -lFhA" }
    - { alias: l,  command: "ls -CF" }

- name: Expand Bash History
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: "{{ item.key }}={{ item.value }}"
    regexp: '^#?\s*{{ item.key }}='
    state: present
  loop:
    - { key: HISTCONTROL,  value: ignoreboth }
    - { key: HISTSIZE,     value: 100000 }
    - { key: HISTFILESIZE, value: 100000 }
    - { key: HISTIGNORE,   value: "'ls:bg:fg:history'" }
