---
- name: Install prometheus node exporter
  apt: 
    pkg:
    - prometheus-node-exporter
    state: present

- name: Create configuration file
  template:
    src: prometheus_node.yml.j2 
    dest: /etc/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Start node exporter
  service:
    name: prometheus-node-exporter
    state: started

