---

- name: 'Ensure the group exists'
  group:
    gid: "{{ remote_gid }}"
    name: "{{ remote_group }}"
    state: present
  tags: create_user

- name: 'Create the user'
  user:
    name: "{{ remote_user }}"
    uid: "{{ remote_uid }}"
    group: "{{ remote_group }}"
    shell: /bin/bash
    home: "{{ home_dir }}"
    generate_ssh_key: yes
  tags: create_user

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ remote_user }}"
    state: present
    key: "{{ lookup('file', remote_user_ssh) }}"
  tags: create_user
