---
# tasks file for nfs4_mount

# this snippet from https://github.com/ome/ansible-role-nfs-mount/blob/master/tasks/main.yml
# bsd-2-clause license

- block:

  - name: Install NFS mount utility (Redhat)
    become: true
    yum:
      name: nfs-utils
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install NFS mount utility (Debian)
    become: true
    apt:
      pkg: nfs-common
      state: present
    when: ansible_os_family == "Debian"
    
  - name: Mount NFS shares
    become: true
    ansible.posix.mount:
      fstype: nfs4
      name: "{{ item.path }}"
      opts: "vers={{ nfs_version }},{{ item.opts | default(nfs_mount_opts) }}"
      src: "{{ item.location }}"
      dump: "{{ item.dump | default(omit) }}"
      passno: "{{ item.passno | default(omit) }}"
      state: "{{ item.state | default( 'mounted' ) }}"
    with_items: "{{ mount_nfs_shares }}"

  when:
    - mount_nfs_shares is defined and (mount_nfs_shares|length>0)