---

- name: "Download promtail tarball ({{ loki_version }})"
  ansible.builtin.get_url:
    url: "https://github.com/grafana/loki/releases/download/{{ loki_version }}/promtail-linux-arm64.zip"
    dest: "{{ loki_working_dir }}"
    mode: '0644'
  become: true

- name: Extract promtail tarball
  ansible.builtin.unarchive:
    src: "{{ loki_working_dir }}/promtail-linux-arm64.zip"
    dest: "{{ loki_exe_dir }}"
    remote_src: yes
  become: true

- name: Install custom promtail config
  ansible.builtin.template:
    src: promtail.yml.j2
    dest: "/etc/promtail.yml"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure group "promtail" exists
  ansible.builtin.group:
    name: promtail
    state: present
  become: true

- name: Add user "promtail"  
  user:
    name: promtail
    group: promtail
    groups: adm
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Promtail nologin User"
    state: present
  become: true

- name: Create storage
  ansible.builtin.file:
    path: /u01/loki
    state: directory
    owner: promtail
    group: promtail
    mode: '0755'
  become: true

- name: Install custom promtail service
  ansible.builtin.template:
    src: systemd-promtail.service.j2
    dest: "/etc/systemd/system/promtail.service"
    owner: promtail
    group: promtail
    mode: '0644'
  become: true

- name: (re)start promtail service
  ansible.builtin.service:
    name: promtail
    state: restarted
    daemon_reload: yes
  become: true
