---

- name: Install custom hosts file
  ansible.builtin.template:
    src: etc_hosts.j2
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ host_file_backup }}"
  become: true
  tags: 
    - create_hostfile
