---

- name: "Include {{ ansible_os_family }} vars"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include_tasks: host_name.yml
  when: pifarm_set_hostname

- include_tasks: host_tz.yml
  when: pifarm_set_timezone

- include_tasks: hosts_file.yml

- block:

  - include_tasks: base_install.yml

  - include_tasks: ruby.yml
    when:
      - ansible_os_family == "Debian"
      - pifarm_install_ruby

  - include_tasks: scipy.yml
    when:
      - ansible_os_family == "Debian"
      - pifarm_install_scipy

  - include_tasks: tmux.yml
    when: pifarm_install_tmux

  - include_tasks: vlans.yml
    when: 
      - pifarm_manage_vlans

  when:
    - pifarm_connected_internet
