---
- hosts: all
  connection: ssh
  gather_facts: no
  become: yes
  become_method: sudo
  serial: 8
  tasks:

  - name: Create facts folder in current directory
    local_action: 
        module: file
        path: './facts'
        state: directory
        owner: "{{ remote_user if remote_user is defined else local_user | default('root') }}"
        group: "{{ remote_group if remote_group is defined else local_group | default('root') }}"

  - name: Collect only facts returned by facter
    setup:
      gather_subset:
        - '!all'
        - '!any'
        - facter
    register: facts_result

  - name: Remove the current previous file
    local_action: 
        module: file
        path: "./facts/{{ facts_result }}"
        state: absent

  - name: Create current facts file
    local_action: 
      module: copy
      content: "{{ facts_result | to_nice_json }}"
      dest: "facts/{{ host_name }}.json"
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ remote_group if remote_group is defined else local_group | default('root') }}"
      mode: 0664

