---
- hosts: all
  connection: ssh
  gather_facts: no
  become: yes
  become_method: sudo
  serial: 8
  tasks:

  - name: Create facts folder in current directory
    local_action: 
        module: file
        path: './facts'
        state: directory
        owner: "{{ hostvars['pi-farmer'].local_user  }}"
        group: "{{ hostvars['pi-farmer'].local_group }}"

  - name: Collect only facts returned by facter
    setup:
      gather_subset:
        - '!all'
        - '!any'
        - facter
    register: facts_result

  - name: Remove the current previous file
    local_action: 
        module: file
        path: "./facts/{{ facts_result }}"
        state: absent

  - name: Create current facts file
    local_action: 
      module: copy
      content: "{{ facts_result | to_nice_json }}"
      dest: "facts/{{ inventory_hostname }}.json"
      owner: "{{ hostvars['pi-farmer'].local_user  }}"
      group: "{{ hostvars['pi-farmer'].local_group }}"
      mode: 0664

