---

- hosts: farmer
  connection: ssh
  gather_facts: yes
  become: yes
  roles:
    - update
    - common
    - farmer-config
    - prometheus-server
      #      when: pifarm_install_dnsmasq

    - dnsmasq

 
