---

- hosts: farmer
  connection: ssh
  gather_facts: yes
  become: yes
  roles:
    - update
    - common
    - farmer_config

    - role: prometheus-server
      when: pifarm_install_prometheus

    - role: dnsmasq
      when: pifarm_install_dnsmasq

 
