---
- hosts:
    - helpers
    - workers
  connection: ssh
  gather_facts: no
  #become: yes
  #become_method: sudo
  serial: 8
  tasks:

    - name: Ping the PiFarm
      action: ping
      debugger: on_failed 
      register: out

    # - name: Print the ping results
    #   ansible.builtin.debug:
    #     var: out
    #     verbosity: 1
