---
- hosts: workers
  connection: ssh
  gather_facts: no
  become: yes
  become_method: sudo
  serial: 8
  tasks:

    - name: Ping the Farma Workers
      action: ping 
      register: out

    - debug:
        var: out
