---

- hosts: workers helpers
  connection: ssh
  become: yes
  gather_facts: no
  tasks:

    - name: Rebooting cluster
      reboot:
        reboot_timeout: 60
      register: reboot_msg

    - name: Reboot results
      debug:
        #msg: "Seconds waiting for reboot {{ elapsed }}"
        var: reboot_msg

    - name: Wait for the machine to come back online
      wait_for_connection:
        connect_timeout: 60
        sleep: 5
        delay: 5
        timeout: 300
