---
# https://docs.docker.com/engine/install/debian/

- hosts: 
    - helper2
  connection: ssh
  gather_facts: true
  become: true
  vars:
    helper_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    repo_key: "https://download.docker.com/linux/debian/gpg"
    repo: "deb https://download.docker.com/linux/debian bullseye stable"
    #rengine_repo: yogeshojha
    rengine_repo: jackaltx
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:

  - name: Install packages
    ansible.builtin.package:
      name: "{{ helper_packages }}"
      state: present
      update_cache: true
    become: true
    register: package_out

  - name: Docker - Import repository key
    ansible.builtin.apt_key:
      url: "{{ repo_key }}"
      state: present
    ignore_errors: true

  - name: Docker - Add repository url
    ansible.builtin.apt_repository:
      repo: "{{ repo }}"
      state: present
      update_cache: true

  - name: Install Docker
    ansible.builtin.package:
      name: "{{ docker_packages }}"
      state: present
      update_cache: true
    become: true
    register: package_out

  - name: "Add {{ worker_user }} to the docker group"
    ansible.builtin.user:
      name: "{{ worker_user }}"
      groups: admin,docker
      append: true
    become: true



  # ===================================================================
  # get specifix version of docker compose

  - name: Download docker-compose
    ansible.builtin.get_url:
      url: "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
      dest: /usr/local/bin/docker-compose
      mode: '755'
    become: true

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/local/bin/docker-compose
      dest: /usr/bin/docker-compose
      state: link
    become: true

  # ===================================================================
  - name: Git clone rengine
    ansible.builtin.git:
      repo: "https://github.com/{{ rengine_repo }}/rengine"
      dest: "/home/{{ worker_user }}/rengine"
      update: false

  - name: Change postgress password
    ansible.builtin.lineinfile:
      path: "/home/{{ worker_user }}/rengine/.env"
      regexp: '^POSTGRES_PASSWORD='
      line: 'POSTGRES_PASSWORD=N0tHardP@ssword'

  - name: Install make
    ansible.builtin.package:
      name: make
      state: present

  - name: Stop service, Remove images, and clean data
    ansible.builtin.command:
      cmd: make prune
      chdir: "/home/{{ worker_user }}/rengine"
    become: true
    register: install_output

  - name: result
    ansible.builtin.debug:
      var: install_output

  - name: make the certs
    ansible.builtin.command:
      cmd: make certs
      chdir: "/home/{{ worker_user }}/rengine"
    become: true
    register: install_output

  - name: result
    ansible.builtin.debug:
      var: install_output

  - name: Compose the docker images
    ansible.builtin.command:
      cmd: make build_clean
      chdir: "/home/{{ worker_user }}/rengine"
    become: true
    register: install_output

  - name: result
    ansible.builtin.debug:
      var: install_output

  - name: Bring up the docker images
    ansible.builtin.command:
      cmd: make up
      chdir: "/home/{{ worker_user }}/rengine"
    become: true
    register: install_output

  - name: result
    ansible.builtin.debug:
      var: install_output

  - name: result
    ansible.builtin.debug:
      msg: "go to the server to create user with 'make username'"
