---

- hosts: workers
  connection: ssh
  become: true
  tasks:

#B1 cli, B2 cli autologin, B3 desktop, B4 desktop autologin

    - name: Set Raspberry Pi to boot to CLI
      shell: raspi-config nonint do_boot_behaviour B4
      async: 1
      poll: 0
      register: result

    - debug:
        var: result

