---

- hosts: all
  serial: 12
  connection: ssh
  become: true
  roles:
    - update

    - role: pi-tools/eeprom
      when:
        - ( ansible_facts.architecture is search("arm") and
          ansible_facts.userspace_bits == "64" ) or
          ansible_facts.architecture is search("aarch64")


