---

- name: set the firmware update config to 'stable'
  copy: 
    src: rpi-eeprom-update
    dest: "/etc/default/rpi-eeprom-update"
    owner: root
    group: root
  become: true

- name: Install rpi-eeprom
  vars:
    packages:
      - "rpi-eeprom"
      - "rpi-eeprom-images"
  apt: 
    pkg: "{{ packages }}"
    state: present

- name: Upgrade Pi Firmware (if required)
  command: rpi-eeprom-update -d -a
  register: upg_out

- debug:
    var: upg_out.stdout_lines

