---
- name: 'Copy .bash_profile to home'
  copy: 
    src: bash_profile
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    owner: "{{ worker_user }}"
    group: "{{ worker_group }}"
    mode: 0644
    backup: yes
  tags: bash_profile
