---
- name: Install prometheus node exporter
  apt: 
    pkg:
    - prometheus-node-exporter
    state: present
    update_cache: true
  become: true

- name: Create /etc/prometheus directory if it does not exist
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create prometheus configuration file
  template:
    src: prometheus_node.yml.j2 
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start node exporter
  service:
    name: prometheus-node-exporter
    state: started
  become: true

