---
- name: stop grafana
  service:
    name: "{{ grafana_service_name }}"
    state: stopped
  become: yes

- name: start grafana
  service:
    name: "{{ grafana_service_name }}"
    state: started
  become: yes

- name: restart grafana
  service:
    name: "{{ grafana_service_name }}"
    state: restarted
  become: yes
