---

#- name: "Include {{ ansible_os_family }} vars"
#  include_vars: "{{ ansible_os_family }}.yml"

# SMELL  use pi facts????

- name: "Update Debian (raspberry pi) JKLJKL"
  include_tasks: "update_pi.yml"
  become: true
  when:
    - pifarm_connected_internet 
    - ansible_os_family == "Debian" 
    #- vars['ansible_distribution_release'] == 'buster'
    #- vars['ansible_machine'] == 'aarch64'


- name: "Update Centos systems"
  include_tasks: "update_centos.yml"
  become: true
  when:
    - pifarm_connected_internet 
    - pifarm_update_centos
    - ansible_os_family == "RedHat"
    - ansible_distribution == "CentOS"
#   - ansible_distribution_major_version == "8"
