---

#- name: "Include {{ ansible_os_family }} vars"
#  include_vars: "{{ ansible_os_family }}.yml"

# SMELL  use pi facts????

- name: "Update Debian OS"
  include_tasks: "update_pi.yml"
  when:
    - pifarm_connected_internet 
    - ansible_os_family == "Debian" 


- name: "Update Centos systems"
  include_tasks: "update_centos.yml"
  when:
    - pifarm_connected_internet 
    - pifarm_update_farmer
    - ansible_os_family == "RedHat"
    - ansible_distribution == "CentOS"
#   - ansible_distribution_major_version == "8"
