---

- name: 'Ensure the group exists'
  become: yes
  group:
    name: "{{ worker_group }}"
    state: present
  tags: create_user

- name: 'Create the user'
  become: yes
  user:
    name: "{{ worker_user }}"
    group: "{{ worker_group }}"
    shell: /bin/bash
    # home: "{{ home_dir }}"
    generate_ssh_key: yes
  tags: create_user

- name: Set authorized key taken from file
  become: yes
  authorized_key:
    user: "{{ worker_user }}"
    state: present
    key: "{{ lookup('file', remote_ssh_access_key) }}"
  tags: create_user

# SMELL....no password sudoer!!!!!!

- name: Add group to the sudoers file
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: "^%{{ worker_group }}"
    line: "%{{ worker_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
