---

# always try to use HTTPS. I'm not sure why the nginx folks don't provide it.
- name: add grafana apt-key
  apt_key: 
    url: https://packages.grafana.com/gpg.key
    state: present 

- name: add grafana apt repository
  apt_repository: 
    repo: 'deb https://packages.grafana.com/oss/deb stable main' 
    state: present 
    filename: nginx 
    update_cache: yes