---

#  SMELL:  this only worked for rasberry pi.
#
- block:

  # SMELL:  only works for debian distro
  - block: 
      - include_vars: "Debian.yml"
      - include_tasks: "install-Debian-repo.yml"
      - include_tasks: "install-Debian.yml"
    when:
      - ansible_os_family == "Debian"

  - name: "Configure Grafana"
    include_tasks: "config.yml"

  - name: "Configure Provisioning"
    include_tasks: "provision.yml"

  - name: "Enable and (re)start grafana service"
    service:
      name: "{{ grafana_service_name }}"
      enabled: yes
      state: restarted
    become: yes

  - name: "Wait for grafana to start"
    wait_for:
      port: "{{ grafana_http_port }}"

  #- name: "Install plugins"
  #  include: "install-plugins.yml"

  when: 
    - pifarm_grafana_server
    - ansible_os_family == "Debian"

