---

- name: Capturing DNSMasq DHCP Leases
  shell: cat /var/lib/dnsmasq/dnsmasq.leases | awk '{ print $4,$3,$2 }'
  register: _dnsmasq_dhcp_leases
  changed_when: false

- name: Parsed DHCP Leases
  debug:
    var: _dnsmasq_dhcp_leases
    verbosity: 1

- name: Updating {{ inventory_dir }}
  template:
    src: hosts.inv.j2
    dest: "hosts.inv"
  # when: pifarms_update_inventory
