---
# tasks file for cluster_prometheus

- include_tasks: node_exporter.yml
  when:
    - pifarm_connected_internet
    - pifarm_node_exporter
  tags:
    - setup_node_exporter

- include_tasks: collector.yml
  when:
    - pifarm_connected_internet
    - pifarm_prometheus_collector
  tags:
    - setup_prometheus_server

