---

- include: nfs_server.yml
- include: node_exporter.yml


#- include: apache.yml
#- include: dnsmasq.yml
#- include: grafana.yml
#- include: node_and_npm.yml
#- include: node-exporter.yml
#- include: rabbitmq-server.yml
