---

- name: 'Ensure the group exists'
  become: yes
  ansible.builtin.group:
    name: "{{ worker_group }}"
    state: present
  tags: create_user

- name: 'Create the user'
  become: yes
  ansible.builtin.user:
    name: "{{ worker_user }}"
    group: "{{ worker_group }}"
    shell: /bin/bash
    # home: "{{ home_dir }}"
    generate_ssh_key: yes
  tags: create_user

- name: Set authorized key taken from file
  become: yes
  ansible.builtin.authorized_key:
    user: "{{ worker_user }}"
    state: present
    key: "{{ lookup('file', remote_ssh_access_key) }}"
  tags: create_user

# SMELL....no password sudoer!!!!!!

- name: Add group to the sudoers file
  become: yes
  lineinfile:
    path: /etc/sudoers
    regexp: "^%{{ worker_group }}"
    line: "%{{ worker_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- block:
  - name: Get the new pi password from secrets
    include_vars: vault.yml
  
  - name: change the pi password
    ansible.builtin.user: 
      name: pi
      update_password: always
      password: "{{ new_passwd|password_hash('sha512') }}"
  when:  change_pi_password
  tags:  reset_pi_password