---

# SMELL: used to turn off WiFI...needs a turn on
# SMELL: adds cgroup, needs a "delete cgroup"

- block:

  - name: "Backup /boot/cmdline.txt to root on Pi ({{ ansible_host }})"
    ansible.builtin.copy :
      src: /boot/cmdline.txt
      dest: /root/cmdline.txt.orig
      mode: '0440'
      remote_src: yes
      force: no
    become: True
    # when: pi_image_setup_cgroup is defined and pi_image_setup_cgroup is True

  - name: Enable cgroup on Pi
    ansible.builtin.command:
      cmd: sed  's/$/ cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1/'  /boot/cmdline.txt
    become: True
    when: pi_image_setup_cgroup is defined and pi_image_setup_cgroup is True
      
  # Set wifi country to "{{ wifi_country }}"
  - name: set wifi country
    ansible.builtin.command: 
      cmd: "raspi-config nonint do_wifi_country {{ wifi_country }}"
    become: True
    when: "wifi_country|default(false)"

  - name: Turn off WiFi
    ansible.builtin.command: 
      cmd: "rfkill block wifi"
    become: True
    changed_when: False
    ignore_errors: True

  when:
    - ansible_os_family == "Debian" 
    - vars['ansible_machine'] == 'aarch64'
