---
- name: restart networking
  service: 
    name: "{{ item }}"
    state: restarted
  loop:
    - networking
    - dhcpcd

- name: restart timezone
  service: 
    name: "{{ item }}"
    state: restarted
  loop:
    - cron
    - rsyslog
    - avahi-daemon
