---
- name: restart networking
  ansible.builtin.service: 
    name: "{{ item }}"
    state: restarted
  loop:
    - networking
    - dhcpcd
  become: true

- name: restart timezone
  ansible.builtin.service: 
    name: "{{ item }}"
    state: restarted
  loop: "{{ pifarm_timezone_services }}"
  become: true
  