galaxy_info:
  author: Haggai Philip Zagury based on Tyler Roscoe
  description: Ansible role to manage grafana on Ubuntu / CentOS 7
  company: Tikal Knowledge LTD

  license: MIT

  min_ansible_version: 2.2.1.0

  platforms:
  - name: EL
    versions:
    - 7
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags: []

dependencies: []
