---
- name: "Install grafand plugins [ when defined ]"
  shell: "{{ grafana_cli }} plugins ls | grep {{ item }} || {{ grafana_cli }} plugins install {{ item }}"
  with_items:
    - "{{ grafana_plugins }}"
  notify: restart grafana
