---

- name: "Download iozone3 tarball ({{ iozone3_ver }})"
  ansible.builtin.get_url:
    url: "http://www.iozone.org/src/current/{{ iozone3_ver }}.tgz"
    dest: "{{ iozone_working_dir }}/iozone3.tgz"
    mode: '0440'
  become: true

- name: Extract iozone3 tarball
  ansible.builtin.unarchive:
    src: "{{ iozone_working_dir }}/iozone3.tgz"
    dest: "{{ iozone_working_dir }}"
    remote_src: yes
  become: true

- name: build iozone3
  command: make linux-arm
  args:
    chdir: "{{ iozone_working_dir }}/{{ iozone3_ver }}/src/current"
    creates: iozone
  become: true
