---

- block:
  - include_tasks: "download_build.yml"
  - include_tasks: "run_benchmark.yml"
  #- include: cleanup.yml

  when: 
    - ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")
