---

- block:
  - include: download_build
  - include: run_benchmark
  - include: cleanup

  when: 
    - ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")
