---

- name: Create facts folder in current directory
  local_action: 
      module: ansible.builtin.file
      path: "{{ lookup('env', 'PWD') }}/benchmarks"
      state: directory
      owner: "{{ hostvars['pi-farmer'].local_user  }}"
      group: "{{ hostvars['pi-farmer'].local_group }}"

- name: "Remove file ({{ iozone_working_dir }}/iozone3_out.txt)"
  ansible.builtin.file:
    path: "{{ iozone_working_dir }}/iozone3_out.txt"
    state: absent
  become: true

- name: "Remove file ({{ iozone_working_dir }}/iozone_{{ inventory_hostname }}.xls)"
  ansible.builtin.file:
    path: "{{ iozone_working_dir }}/iozone_{{ inventory_hostname }}.xls"
    state: absent
  become: true

- name: RUNNING iozone3 test nfs mount
  command: "./iozone {{iozone_flags }} -f {{ iozone_testmount }}/testfile_{{ inventory_hostname }} -b {{ iozone_working_dir }}/iozone_{{ inventory_hostname }}.xls | tee {{ iozone_working_dir }}/iozone3_out.txt"
  args:
    chdir: "{{ iozone_working_dir }}/{{ iozone3_ver }}/src/current"
  register: myoutput
  failed_when:
    - myoutput.rc != 0 or myoutput.failed
  become: true

#- debug:
#    var: myoutput
#  verbosity: 1

- name: store locally iozone command results log
  local_action: 
    module: ansible.builtin.copy
    content: "{{ myoutput.stdout_lines | join('\n') }}" 
    dest: "{{ lookup('env', 'PWD') }}/benchmarks/iozone_{{ inventory_hostname }}.log"

- name: "fstat ({{ iozone_working_dir }}/iozone_{{ inventory_hostname }}.xls)"
  ansible.builtin.stat:
    path: "{{ iozone_working_dir }}/iozone_{{ inventory_hostname }}.xls"
  register: xls_file

- debug:
    msg: "iozone output does not exist: {{ iozone_working_dir }}/iozone_{{ inventory_hostname }}.xls"
  when: not xls_file.stat.exists

- name: store locally iozone excel ouput xls
  ansible.builtin.fetch:
    src: "{{ iozone_working_dir }}/iozone_{{ inventory_hostname }}.xls"
    dest: "{{ lookup('env', 'PWD') }}/benchmarks/"
    flat: yes
  when: xls_file.stat.exists