---
- name: Install prometheus node exporter
  apt: 
    pkg:
    - prometheus-node-exporter
    state: present
    update_cache: true
  become: true

- name: Create configuration file
  template:
    src: prometheus_server.xml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Restart node exporter

