---
- name: Install apache
  apt: 
    name: apache2
    state: present
    update_cache: ture
  become: true
  tags: apache

- name: Stop apache2
  service:
    name: apache2
    state: stopped
  become: true
  tags: apache

- name: Disable default config 
  command: a2dissite 000-default.conf
  tags: apache

- copy: 
    src: raspifarm.conf
    dest: /etc/apache2/sites-available/raspifarm.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true
  tags: apache

- name: Enable raspifarm config
  command: a2ensite raspifarm.conf
  become: true
  tags: apache

- name: Start apache
  service:
    name: apache2
    state: started
  become: true
  tags: apache

- name: Reload apache
  service: 
    name: apache2
    state: reloaded
  become: true
  tags: apache
