---
- name: Install basic packages
  ansible.builtin.package: 
    name: "{{ pifarm_common_pkgs }}"
    state: present
    update_cache: true
  become: true
  register: package_out
  

- ansible.builtin.debug:
    var: package_out
    verbosity: 1

