---
- name: Install basic packages
  apt: 
    name: "{{ pifarm_common_pkgs }}"
    state: present
    update_cache: true
  become: true
  register: apt_out
  tags:
    - basic

- debug:
    var: apt_out

