---
- name: Install basic packages
  package: 
    name: "{{ pifarm_common_pkgs }}"
    state: present
    update_cache: true
  become: true
  register: package_out
  tags:
    - basic

- debug:
    var: package_out

