---
  
- name: Install dnsmasq
  ansible.builtin.apt: 
    name: dnsmasq
    state: present

- name: Stop dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: stopped

- name: Install configuration File
  ansible.builtin.copy: 
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
