---

- name: "Include {{ ansible_os_family }} vars"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include: host_name.yml
  when: pifarm_set_hostname

- include: host_tz.yml
  when: pifarm_set_timezone

- include: hosts_file.yml

- block:

  - include: base_install.yml

  - include: ruby.yml
    when:
      - ansible_os_family == "Debian"
      - pifarm_install_ruby

  - include: scipy.yml
    when:
      - ansible_os_family == "Debian"
      - pifarm_install_scipy

#  - include: openmpi.yml
#    when:
#      - ansible_os_family == "Debian"
#      - pifarm_install_mpi

  - include: tmux.yml
    when: pifarm_install_tmux

  - include: vlans.yml
    when: 
      - pifarm_manage_vlans

  # - include: java.yml
  # - include: pip.yml

  when:
    - pifarm_connected_internet
