---

- include: htop.yml
- include: tree.yml
- include: wget.yml
- include: vim.yml
- include: ruby.yml
- include: git.yml
#- include: java.yml
#- include: pip.yml
- include: scipy.yml
- include: dnsutils.yml
- include: mpi4py.yml
