---

- include: htop.yml
- include: tree.yml
- include: wget.yml
- include: vim.yml
- include: ruby.yml
- include: git.yml
#- include: jjava.yml
#- include: pip.yml
- include: scipy.yml
- include: dnstools.yml
- include: mpi4py.yml
- include: node-exporter.yml
