---

- block:

  - name: Install pip
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      force: yes
    become: true
    with_items:
      - "python-pip"
      - "python-dev"
      - "build-essential"

  - name: Upgrade pip
    ansible.builtin.pip:
      name: pip
      state: present

  - name: Install virtualenv
    ansible.builtin.pip:
      name: virtualenv
      state: present

    tags:
      - install_pip



