---
- name: Install pip
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - "python-pip"
    - "python-dev"
    - "build-essential"
  tags:
    - basic
    - developer

- name: Upgrade pip
  pip:
    name: pip
    state: present
  tags:
    - basic
    - developer

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present
  tags:
    - basic
    - developer



