---

- name: Install ruby
  package: 
    name: ruby
    state: present
    update_cache: true
  register: package_out
  become: true

- debug:
    var: package_out
    verbosity: 1


  #- name: Install rubygems
  #  apt: 
  #    name: rubygems
  #    state: present
  #    update_cache: true
  #  become: true
