---

- name: Install ruby
  apt: 
    name: ruby
    state: present
    force: yes
    update_cache: true
  become: true

  #- name: Install rubygems
  #  apt: 
  #    name: rubygems
  #    state: present
  #    update_cache: true
  #  become: true
