---

- name: Install scipy
  apt: 
    ansible.builtin.pkg:
    - "python-numpy"
    - "python-pickleshare"
    - "python-scipy"
    - "python-matplotlib"
    state: present
    update_cache: true
  become: true
  register: package_out

- name: Scipy Package install output
  ansible.builtin.debug:
    var: package_out
    verbosity: 1
