---

- name: Install scipy for python 3
  ansible.builtin.apt: 
    pkg:
    - "python3-numpy"
    - "python3-pickleshare"
    - "python3-scipy"
    - "python3-matplotlib"
    state: present
    update_cache: true
  become: true
  register: package_out

- name: Scipy Package install output
  ansible.builtin.debug:
    var: package_out
    verbosity: 1
