---

- block:

  - name: Install SNMPD
    ansible.builtin.apt: 
      name: snmpd
      state: present


  - name: Stop SNMPD
    ansible.builtin.service:
      name: snmpd
      state: stopped


  - name: cofiguration 
    ansible.builtin.copy: 
      src: snmpd.conf
      dest: /etc/snmp/snmpd.conf
      owner: root
      group: root
      mode: 0600
      backup: yes


  - name: Start SNMPD
    service:
      name: snmpd
      state: started

  tags:
    - perfmon