---
# dnsmasq 

- block:

  - name: Install dnsmasq
    package: 
      name: dnsmasq
      state: present

  - name: Stop dnsmasq
    service:
      name: dnsmasq
      state: stopped

  - copy: 
      src: dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Start dnsmasq
    service:
      name: dnsmasq
      state: started

  when:
    - pifarm_install_dnsmasq
