---
- name: 'Copy .bash_profile to home'
  copy: 
    src: bash_profile
    dest: "{{ home_dir }}/.bash_profile"
    owner: farmer
    group: admin
    mode: 0644
    backup: yes
  tags: bash_profile
