---
- hosts: all
  connection: ssh
  gather_facts: no
  become: yes
  become_method: sudo
  serial: 8
  tasks:

  - name: Create facts folder in current directory
    local_action: 
        module: ansible.builtin.file
        path: "{{ lookup('env', 'PWD') }}/facts"
        state: directory
        owner: "{{ hostvars['pi-farmer'].local_user  }}"
        group: "{{ hostvars['pi-farmer'].local_group }}"

  - name: Collect only facts returned by facter
    ansible.builtin.setup:
      gather_subset:
        - '!all'
        - '!any'
        - facter
    register: facts_result
    
  - name: Remove the previous fact files
    local_action: 
        module: file
        path: "{{ lookup('env', 'PWD') }}/facts/{{ facts_result }}"
        state: absent

  - name: Create current facts files
    local_action: 
      module: ansible.builtin.copy
      content: "{{ facts_result | to_nice_json }}"
      dest: "{{ lookup('env', 'PWD') }}/facts/{{ inventory_hostname }}.json"
      owner: "{{ hostvars['pi-farmer'].local_user  }}"
      group: "{{ hostvars['pi-farmer'].local_group }}"
      mode: 0664
