---
# handlers file for cluster_prometheus

- name: Restart prometheus service
  ansible.builtin.service:
    name: prometheus
    state: restarted
  become: true

- name: Restart node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted
  become: true
