---
- hosts: raspifarm-master
  remote_user: farmer
  vars:
    rabbit_user: admin
    rabbit_password: farmer
  become: yes
  become_method: sudo
  serial: 8
  tasks:
    - include: tasks/rabbitmq-server.yml

    - name: configure RabbitMQ Server
      command: "{{ item }}"
      with_items: 
          - rabbitmq-plugins enable rabbitmq_management
          - rabbitmqctl add_user {{ rabbit_user }} {{ rabbit_password }}
          - rabbitmqctl set_user_tags {{ rabbit_user }} administrator
          - rabbitmqctl set_permissions -p / {{ rabbit_user }} ".*" ".*" ".*"
      register: myoutput

    - debug: 
        var: myoutput
