---

- block:

  - name: Install nfs-server
    ansible.builtin.apt:
      name:
        - nfs-kernel-server
        - rpcbind
      state: present
      update_cache: true
    become: true
  
## SMELL....the share is hardcoded.
## needs to be done for each host

##  This is for the pi only today

  - name: Configure nfs-server
    ansible.builtin.template: 
      src: exports.j2
      dest: /etc/exports
      owner: root
      group: root
      mode: 0644
      backup: yes
    become: true
    notify:
      - Reload nfs server

  when: 
    - export_nfs_shares
    - nfs_exports is defined and (nfs_exports|length>0)
    - ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")
