---

- block:

  - name: Install nfs-server
    ansible.builtin.apt:
      name:
        - nfs-kernel-server
        - rpcbind
      state: present
      update_cache: true
    become: true
  
  - name: Configure nfs-server
    ansible.builtin.copy: 
      src: exports
      dest: /etc/exports
      owner: root
      group: root
      mode: 0644
      backup: yes
    become: true
    notify:
      - Reload nfs server

  when: export_nfs_share
  tags: nfs_share